//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws14_MedgikWorkes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnikis
    {
        public int IdSotrudnik { get; set; }
        public string IdDolznost { get; set; }
        public string Должность { get; set; }
        public string Сотрудник { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Телефон { get; set; }
    }
}
