//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws14_MedgikWorkes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ws14Entities1 : DbContext
    {
        public static ws14Entities1 _context;
        public ws14Entities1()
            : base("name=ws14Entities1")
        {
        }
        public static ws14Entities1 GetContext()
        {
            if (_context == null)
            {
                _context = new ws14Entities1();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sotrudnikis> Sotrudnikis { get; set; }
    }
}
